require: rubocop-rspec
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/application.rb'
    - 'config/environments/**/*'
