require: rubocop-rspec
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/Capybara/FeatureMethods:
  Exclude:
    - 'spec/**/*'
RSpec/NestedGroups:
  Exclude:
    - 'spec/controllers/questions_controller_spec.rb'
Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/20201214102102_add_devise_to_users.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/application.rb'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
